# Project information
site_name: Бібліотека проекту
site_description: Каталог ресурсів та база знань команди проекту.
site_author: Антон Паліхов aka Palant
# Repository
repo_name: 'palikhov/Library-project-uken'
repo_url: 'https://github.com/palikhov/Library-project-uken'
# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Team Awesome'

nav:
    - Головна: index.md
  
    - Бібліотека проекту:
        - ОСНОВНІ КНИЖКИ РОСІЙСЬКОЮ: library/books-russian.md  
        - Каталог інтернет посилань: library/links.md
        - Каталог книг: library/ebooks.md
        - Каталог книг 2: library/books.md
        - Шаблони: library/templates.md
        - Microsoft Dynamics AX 2012 - довідник для професіонала: library/ms-dynamics-ax-2012-rus-book.md
    - Навчальні матеріали:
        - Як дізнатися структуру таблиці данних: education/example-table-names.md
        - Як має працювати KPI: education/example-kpi-correct.md
        - Допоміжні посилання при роботі з MKDocs: education/useful-links-mkdocs.md
        - Інколи треба й жартувати: education/jokes.md
    - Закупівлі: purchasing/index.md
    - Управління та облік по проектам:
        - Модуль Управління та облік по проектам: project-management-accounting\index.md
        - Корисні посилання на документацію: project-management-accounting/docs-project-management.md
        - Опис моделі інвестиційної діяльності: project-management-accounting/investments-program.md 
        - Приклади використання розмітки: project-management-accounting/examples-markdown-extensions.md
        - Модифікації програмного коду: project-management-accounting/pm-modifications.md
        - Запис відео з екрану за допомогою PowerPoint: project-management-accounting/powerpoint-video-tutorials.md
    - Бюджетування: budget_managing/index.md
    - Складання та управлыння БРГК: treasury/education-cash-flow.md
    - Кадровий облік та зарплата: human_resources/index.md
    - Бухгалтерський облік: accounting/index.md
    - Ліцензія: license.md
    - Щось: media/index.md
    - Інше щось: media/education/index.md
    - Звіт: status\report.md
# Link as comment before release 

# Configuration
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo:
    icon: 'library_books'
  language: 'uk'
  feature:
    tabs: true
    
# Customization
extra:
  search:
    language: 'en, ru, uk'
  social:
    - type: 'github'
      link: 'https://github.com/palikhov'
    - type: 'twitter'
      link: 'https://twitter.com/AVPalikhov'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/avpalikhov'

# Extensions
markdown_extensions:
    - smarty
    - abbr
    - attr_list
    - def_list
    - fenced_code
    - footnotes
    - tables
    - admonition
    - meta
    - wikilinks
    - codehilite:
          guess_lang: false
    - toc:
        permalink: True
    - sane_lists
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde

extra_javascript: [extra.js]

extra_css:
    - css/custom.css
